src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
#[ORM\Id]
#[ORM\GeneratedValue]
#[ORM\Column]
private ?int $id = null;

#[ORM\Column(length: 100)]
private ?string $nom_cours = null;

#[ORM\Column(type: Types::TEXT)]
private ?string $description = null;

#[ORM\Column]
private ?float $prix = null;

#[ORM\OneToMany(mappedBy: 'cours', targetEntity: Reservation::class)]
private Collection $reservations;

#[ORM\Column(length: 255)]
private ?string $slug_cours = null;

#[ORM\Column(length: 255)]
private ?string $imageName = null;

public function __construct()
{
    $this->reservations = new ArrayCollection();
}

public function getId(): ?int
{
    return $this->id;
}

public function getNomCours(): ?string
{
    return $this->nom_cours;
}

public function setNomCours(string $nom_cours): self
{
    $this->nom_cours = $nom_cours;

    return $this;
}

public function getDescription(): ?string
{
    return $this->description;
}

public function setDescription(string $description): self
{
    $this->description = $description;

    return $this;
}

public function getPrix(): ?float
{
    return $this->prix;
}

public function setPrix(float $prix): self
{
    $this->prix = $prix;

    return $this;
}

/**
 * @return Collection<int, Reservation>
 */
public function getReservations(): Collection
{
    return $this->reservations;
}

public function addReservation(Reservation $reservation): self
{
    if (!$this->reservations->contains($reservation)) {
        $this->reservations->add($reservation);
        $reservation->setCours($this);
    }

    return $this;
}

public function removeReservation(Reservation $reservation): self
{
    if ($this->reservations->removeElement($reservation)) {
        // set the owning side to null (unless already changed)
        if ($reservation->getCours() === $this) {
            $reservation->setCours(null);
        }
    }

    return $this;
}

public function getPrixFois100(): string
{
return number_format($this->prix * 100, 2, '.', '');
}

public function getSlugCours(): ?string
{
    return $this->slug_cours;
}

public function setSlugCours(string $slug_cours): self
{
    $this->slug_cours = $slug_cours;

    return $this;
}

public function __toString(): string
{
    return $this->getNomCours();
}

public function getImageName(): ?string
{
    return $this->imageName;
}

public function setImageName(string $imageName): self
{
    $this->imageName = $imageName;

    return $this;
}


}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
#[ORM\Id]
#[ORM\GeneratedValue]
#[ORM\Column]
private ?int $id = null;

#[ORM\Column(type: Types::DATETIME_MUTABLE)]
private ?\DateTimeInterface $dt_resa = null;

#[ORM\Column(type: Types::DATETIME_MUTABLE)]
private ?\DateTimeInterface $dt_cours = null;

#[ORM\ManyToOne(inversedBy: 'reservations')]
#[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
private ?Cours $cours = null;

#[ORM\ManyToOne(inversedBy: 'reservations')]
#[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
private ?User $user = null;

#[ORM\Column(length: 250)]
private ?string $payement_method = null;

#[ORM\OneToOne(mappedBy: 'reservation', cascade: ['persist', 'remove'])]
private ?Payement $payement = null;

#[ORM\Column(nullable: false, options: ["default" => 0])]
private ?bool $isPaid = null;

#[ORM\Column(length: 15, nullable: true)]
private ?string $user_phone = null;

#[ORM\Column(length: 100, nullable: true)]
private ?string $user_firstname = null;

#[ORM\Column(length: 100, nullable: true)]
private ?string $user_lastname = null;

#[ORM\Column(length: 150, nullable: true)]
private ?string $user_adress = null;

public function getId(): ?int
{
    return $this->id;
}

public function getDtResa(): ?\DateTimeInterface
{
    return $this->dt_resa;
}

public function setDtResa(\DateTimeInterface $dt_resa): self
{
    $this->dt_resa = $dt_resa;

    return $this;
}

public function getDtCours(): ?\DateTimeInterface
{
    return $this->dt_cours;
}

public function setDtCours(\DateTimeInterface $dt_cours): self
{
    $this->dt_cours = $dt_cours;

    return $this;
}

public function getCours(): ?Cours
{
    return $this->cours;
}

public function setCours(?Cours $cours): self
{
    $this->cours = $cours;

    return $this;
}

public function getUser(): ?User
{
    return $this->user;
}

public function setUser(?User $user): self
{
    $this->user = $user;

    return $this;
}

public function getPayement(): ?Payement
{
    return $this->payement;
}

public function setPayement(Payement $payement): self
{
    // set the owning side of the relation if necessary
    if ($payement->getReservation() !== $this) {
        $payement->setReservation($this);
    }

    $this->payement = $payement;

    return $this;
}

public function getPayementMethod(): ?string
{
    return $this->payement_method;
}

public function setPayementMethod(string $payement_method): self
{
    $this->payement_method = $payement_method;

    return $this;
}

public function isIsPaid(): ?bool
{
    return $this->isPaid;
}

public function setIsPaid(bool $isPaid): self
{
    $this->isPaid = $isPaid;

    return $this;
}

public function getUserPhone(): ?string
{
    return $this->user_phone;
}

public function setUserPhone(string $user_phone): self
{
    $this->user_phone = $user_phone;

    return $this;
}

public function getUserFirstname(): ?string
{
    return $this->user_firstname;
}

public function setUserFirstname(string $user_firstname): self
{
    $this->user_firstname = $user_firstname;

    return $this;
}

public function getUserLastname(): ?string
{
    return $this->user_lastname;
}

public function setUserLastname(string $user_lastname): self
{
    $this->user_lastname = $user_lastname;

    return $this;
}

public function getUserAdress(): ?string
{
    return $this->user_adress;
}

public function setUserAdress(string $user_adress): self
{
    $this->user_adress = $user_adress;

    return $this;
}
}

templates/invoice/invoice.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Facture</title>
</head>
<body>
    
</body>
</html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Facture</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .invoice-header {
            text-align: center;
            margin-bottom: 20px;
        }
        .invoice-details {
            width: 100%;
            border-collapse: collapse;
        }
        .invoice-details th, .invoice-details td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        .invoice-details th {
            background-color: #f0f0f0;
        }
        .footer {
            position: fixed;
            bottom: 0;
        }
    </style>
</head>
<body>
    <div class="invoice-header">
        {# <img src="{{ asset('public/img/image-centrale2.png') }}" alt="Logo" /> #}
        <h1>Facture</h1>
        <p>Date de Réservation : {{ reservation.dtResa|date('d-m-Y') }}</p>
    </div>

    <table class="invoice-details">

        <tr>
            <th>Madame, Monsieur</th>
            <td>{{ reservation.userLastname}} {{ reservation.userFirstname}}</td>
        </tr>

        <tr>
            <th>Votre cours aura lieu le </th>
            <td>{{ reservation.dtCours|date('d-m-Y H:i') }}</td>
        </tr>

        <tr>
            <th>Votre réservation concerne le cours </th>
            <td>{{ reservation.cours.nomCours }}</td>
        </tr> 

        <tr>
            <th>Lieu du cours</th>
            <td>{{ reservation.userAdress}}</td>
        </tr>

        <tr>
            <th>Votre numéro de téléphone</th>
            <td>{{ reservation.userPhone}}</td>
        </tr>

        <tr>
            <th>Méthode de Paiement</th>
            <td>{{ reservation.payementMethod }}</td>
        </tr>

        <tr>
            <th>Prix</th>
              <td>{{ reservation.cours.prix }}€</td>
        </tr>

    </table>
    <div class="footer">
        <p>Contact : DouceurDeLune@gmail.com</p>
    </div>
    
</body>
</html>