src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
#[ORM\Id]
#[ORM\GeneratedValue]
#[ORM\Column]
private ?int $id = null;

#[ORM\Column(length: 100)]
private ?string $nom_cours = null;

#[ORM\Column(type: Types::TEXT)]
private ?string $description = null;

#[ORM\Column]
private ?float $prix = null;

#[ORM\OneToMany(mappedBy: 'cours', targetEntity: Reservation::class)]
private Collection $reservations;

#[ORM\Column(length: 255)]
private ?string $slug_cours = null;

#[ORM\Column(length: 255)]
private ?string $imageName = null;

public function __construct()
{
    $this->reservations = new ArrayCollection();
}

public function getId(): ?int
{
    return $this->id;
}

public function getNomCours(): ?string
{
    return $this->nom_cours;
}

public function setNomCours(string $nom_cours): self
{
    $this->nom_cours = $nom_cours;

    return $this;
}

public function getDescription(): ?string
{
    return $this->description;
}

public function setDescription(string $description): self
{
    $this->description = $description;

    return $this;
}

public function getPrix(): ?float
{
    return $this->prix;
}

public function setPrix(float $prix): self
{
    $this->prix = $prix;

    return $this;
}

/**
 * @return Collection<int, Reservation>
 */
public function getReservations(): Collection
{
    return $this->reservations;
}

public function addReservation(Reservation $reservation): self
{
    if (!$this->reservations->contains($reservation)) {
        $this->reservations->add($reservation);
        $reservation->setCours($this);
    }

    return $this;
}

public function removeReservation(Reservation $reservation): self
{
    if ($this->reservations->removeElement($reservation)) {
        // set the owning side to null (unless already changed)
        if ($reservation->getCours() === $this) {
            $reservation->setCours(null);
        }
    }

    return $this;
}

public function getPrixFois100(): string
{
return number_format($this->prix * 100, 2, '.', '');
}

public function getSlugCours(): ?string
{
    return $this->slug_cours;
}

public function setSlugCours(string $slug_cours): self
{
    $this->slug_cours = $slug_cours;

    return $this;
}

public function __toString(): string
{
    return $this->getNomCours();
}

public function getImageName(): ?string
{
    return $this->imageName;
}

public function setImageName(string $imageName): self
{
    $this->imageName = $imageName;

    return $this;
}


}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
#[ORM\Id]
#[ORM\GeneratedValue]
#[ORM\Column]
private ?int $id = null;

#[ORM\Column(type: Types::DATETIME_MUTABLE)]
private ?\DateTimeInterface $dt_resa = null;

#[ORM\Column(type: Types::DATETIME_MUTABLE)]
private ?\DateTimeInterface $dt_cours = null;

#[ORM\ManyToOne(inversedBy: 'reservations')]
#[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
private ?Cours $cours = null;

#[ORM\ManyToOne(inversedBy: 'reservations')]
#[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
private ?User $user = null;

#[ORM\Column(length: 250)]
private ?string $payement_method = null;

#[ORM\OneToOne(mappedBy: 'reservation', cascade: ['persist', 'remove'])]
private ?Payement $payement = null;

#[ORM\Column(nullable: false, options: ["default" => 0])]
private ?bool $isPaid = null;

#[ORM\Column(length: 15, nullable: true)]
private ?string $user_phone = null;

#[ORM\Column(length: 100, nullable: true)]
private ?string $user_firstname = null;

#[ORM\Column(length: 100, nullable: true)]
private ?string $user_lastname = null;

#[ORM\Column(length: 150, nullable: true)]
private ?string $user_adress = null;

public function getId(): ?int
{
    return $this->id;
}

public function getDtResa(): ?\DateTimeInterface
{
    return $this->dt_resa;
}

public function setDtResa(\DateTimeInterface $dt_resa): self
{
    $this->dt_resa = $dt_resa;

    return $this;
}

public function getDtCours(): ?\DateTimeInterface
{
    return $this->dt_cours;
}

public function setDtCours(\DateTimeInterface $dt_cours): self
{
    $this->dt_cours = $dt_cours;

    return $this;
}

public function getCours(): ?Cours
{
    return $this->cours;
}

public function setCours(?Cours $cours): self
{
    $this->cours = $cours;

    return $this;
}

public function getUser(): ?User
{
    return $this->user;
}

public function setUser(?User $user): self
{
    $this->user = $user;

    return $this;
}

public function getPayement(): ?Payement
{
    return $this->payement;
}

public function setPayement(Payement $payement): self
{
    // set the owning side of the relation if necessary
    if ($payement->getReservation() !== $this) {
        $payement->setReservation($this);
    }

    $this->payement = $payement;

    return $this;
}

public function getPayementMethod(): ?string
{
    return $this->payement_method;
}

public function setPayementMethod(string $payement_method): self
{
    $this->payement_method = $payement_method;

    return $this;
}

public function isIsPaid(): ?bool
{
    return $this->isPaid;
}

public function setIsPaid(bool $isPaid): self
{
    $this->isPaid = $isPaid;

    return $this;
}

public function getUserPhone(): ?string
{
    return $this->user_phone;
}

public function setUserPhone(string $user_phone): self
{
    $this->user_phone = $user_phone;

    return $this;
}

public function getUserFirstname(): ?string
{
    return $this->user_firstname;
}

public function setUserFirstname(string $user_firstname): self
{
    $this->user_firstname = $user_firstname;

    return $this;
}

public function getUserLastname(): ?string
{
    return $this->user_lastname;
}

public function setUserLastname(string $user_lastname): self
{
    $this->user_lastname = $user_lastname;

    return $this;
}

public function getUserAdress(): ?string
{
    return $this->user_adress;
}

public function setUserAdress(string $user_adress): self
{
    $this->user_adress = $user_adress;

    return $this;
}
}

templates/pagesInfo/atelier-de-portage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Le portage{% endblock %}

{% block body_class %}page-color-portage{% endblock %}

{% block body %}

{% block bandeau %}
    <div class="bandeau-portage"></div>
{% endblock %}

<div class="container1">
<div class="enfant pastel-blue1 enfant-portage" data-aos="fade-right" data-aos-duration="2000">
    <h2>Le portage physiologique</h2> 
    <p> <br>
        "Un bébé bien porté deviendra un enfant bien portant." <br><br>  Le terme “portage physiologique” est en fait un raccourci. Il faudrait normalement parler de portage respectant la position physiologique du bébé/enfant. C'est-à-dire, la posture naturelle prise par l'enfant en fonction de son âge, de son tonus, du développement de sa colonne vertébrale, de l'ouverture de son bassin, de son éveil et des ses capacités musculaires.
        Je rappelle une notion très importante à connaitre quand on devient parent : le nouveau-né est compétent et dépendant. Il sait faire et comprendre plein de choses notamment sur les plans sensoriel et relationnel. Cependant, le petit humain reste complètement dépendant des adultes. Il ne se déplace pas seul, ne se nourrit pas seul, ne régule pas ses émotions, sa température tout seul,...
        Le portage s'adapte au bébé sur le plan physique comme sur le plan émotionnel en répondant à la plupart de ses besoins fondamentaux. C'est le point de départ du développement moteur ex-utéro. <br><br> 
    </p>
</div>
<div class="enfant" data-aos="fade-left" data-aos-duration="2000">
    <img class="image-responsive img-hover" src="/img/portageminiature.webp" alt="Image d'une femme qui tient sont enfant contre elle dans une écharpe de portage">
</div>
</div>
<div class="container2">
<div class="enfant pastel-blue2" data-aos="fade-right" data-aos-duration="2000">
    <h2 class="enfant-portage">Pourquoi suivre un atelier ?</h2>  
    <ul> <br>
        <li><span  class="span-portage">Tester et pratiquer :</span > Apprendre les gestes techniques et découvrir tous les moyens de portage c'est bien. Mais pratiquer et vivre l'expérience permet de vraiment s'approprier le portage.
            Je m'adapte entièrement à vous et vous propose d'essayer tous les moyens de portage existants afin de trouver LE bon, LE meilleur pour répondre aux besoins de votre famille ! </li> <br>
        <li><span class="span-portage">S'informer - porter en sécurité</span> Pour trouver les bonnes informations à propos du portage et de tous les moyens disponibles, rien de mieux qu'une professionnelle formée qui met ses connaissances à jour en continu.
            Le portage peut être technique et intégrer quelques notions de sécurité est indispensable. C'est également l'occasion d'apprendre à porter bébé en respectant sa physiologie et son développement psycho-moteur tout en gardant un maximum de confort pour le porteur.</li><br>
        <li><span class="span-portage">Avoir confiance en soi :</span> Vous et votre bébé possédez toutes les compétences pour vivre le portage au mieux ! Pour oser, il manque en général juste un peu d'accompagnement et d'encouragements.
            Entre doutes, peurs, gestes techniques et questions, je vous guide progressivement vers un portage tout en sérénité.  </li><br>
    </ul>
</div>
<div class="enfant pastel-blue3 enfant-portage" data-aos="fade-left" data-aos-duration="2000">
    <h2>Les bienfaits pour le bébé :</h2>  
    <ul> <br>
        <li><span class="span-portage">Renforce le lien parent-enfant :</span> Le contact physique rapproché encourage le développement de l'attachement entre le parent et le bébé.</li> <br>
        <li><span class="span-portage">Stimule le développement physique :</span> Le portage permet au bébé d'adopter une position physiologique naturelle, ce qui peut favoriser le développement de ses hanches et de sa colonne vertébrale.</li><br>
        <li><span class="span-portage">Favorise l'équilibre et la coordination :</span> Le mouvement constant aide le bébé à développer son sens de l'équilibre et sa coordination.</li><br>
        <li><span class="span-portage">Favorise l'interaction sociale :</span> Porter votre bébé à la hauteur des yeux vous permet de mieux interagir avec lui et lui offre une perspective intéressante sur le monde.</li><br>
        <li><span class="span-portage">Apaise et réconforte le bébé :</span> Le contact rapproché avec le parent peut aider à calmer un bébé agité, à réduire les pleurs et à favoriser un meilleur sommeil.</li><br>
        <li><span class="span-portage">Facilite l'allaitement :</span> Le portage peut faciliter l'allaitement en permettant un accès facile au sein et en favorisant la production de lait grâce au contact peau à peau.</li> <br>
    </ul>
</div>
</div>

<div id="calendar"></div>

{# script afficher le calendar #}
<script src="{{ asset('js/calendar.js') }}"></script>
{% endblock %}

templates/pagesInfo/cercle-mamans-bebes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Le cercle des mamans{% endblock %}

{% block body_class %}page-color-cercle{% endblock %}

{% block body %}

{% block bandeau %}
    <div class="bandeau-cercle"></div>
{% endblock %}

<div class="container1">
<div class="enfant pastel-red1" data-aos="fade-right" data-aos-duration="2000">
    <h2 class="enfant-cercle">Présentation du cours :</h2> 
    <p> <br>
        "Cette possibilité que la maternité ne soit pas un don inné, qu'elle se construise avec l'enfant dans le doute et la folie, dans le tâtonnement de la raison du plus aimant."<br><br>
        Comme l'adolescence qui est le passage de l'enfance à l'âge adulte, la matrescence est une période de vie. Elle s'accompagne de changements physiques et psychiques avec lesquels il faut faire "co-naissance". Cette naissance en tant que mère nécessite du temps et du soutien. La maternité n'est pas instinctive, pas toujours rose. 
    </p>

    <ul>
        <li><span class="span-cercle">-</span> Votre bébé a entre 0 et 6 mois ?</li>
        <li><span class="span-cercle">-</span> Vous vous sentez seule ? Désemparée ?</li>
        <li><span class="span-cercle">-</span> Vous aimeriez qu'on vous donne le mode d'emploi de cette petite boule de bébé ?</li>
        <li><span class="span-cercle">-</span> Vous avez besoin de vous sentir soutenue et écoutée ?</li>
        <li><span class="span-cercle">-</span> Trop de jugements, de conseils, d'injonctions, vous êtes perdue ?</li>
    </ul> <br> <br>
</div>
<div class="enfant" data-aos="fade-left" data-aos-duration="2000">
    <img class="image-responsive img-hover" src="/img/famille-assis-maison-lit.jpg" alt="Image d'une famille qui joue avec leurs 2 bébés dont un sur le tapis qui avance">
</div>
</div>
<div class="container2">
<div class="enfant pastel-red2" data-aos="fade-right" data-aos-duration="2000">
    <h2 class="enfant-cercle">Plusieurs sensations et émotions</h2>  
    <ul> <br>
        <li><span class="span-cercle">-</span> Des moments cocooning pour maman et bébé</li> <br>
        <li><span class="span-cercle">-</span> Des rires, des émotions et des larmes</li><br>
        <li><span class="span-cercle">-</span> Des échanges de mots et de maux</li><br>
        <li><span class="span-cercle">-</span> De l'écoute et de la bienveillance</li><br>
        <li><span class="span-cercle">-</span> Du partage, de l'entraide</li><br>
        <li><span class="span-cercle">-</span> Des activités ludiques et/ou créatives</li><br>
        <li><span class="span-cercle">-</span> La création d'un lien fort avec bébé</li><br><br>
    </ul>
</div>
<div class="enfant pastel-red3" data-aos="fade-left" data-aos-duration="2000">
    <h2 class="enfant-cercle">Le cercle, c'est quoi ?</h2>  
    <ul> <br>
        <li><span class="span-cercle">-</span> 4 rencontres de 2h pendant 1 mois</li> <br>
        <li><span class="span-cercle">-</span> Un groupe privé Whatsapp pour chaque cercle</li><br>
        <li><span class="span-cercle">-</span> 3 à 6 mamans et leur bébé de 0 à 6 mois</li><br>
        <li><span class="span-cercle">-</span> Un coin change avec tout le nécessaire</li><br>
        <li><span class="span-cercle">-</span> Des coussins, des plaids, des tapis...</li><br>
        <li><span class="span-cercle">-</span> Du thé/tisane et des gourmandises healthy</li><br>
        <li><span class="span-cercle">-</span> Plein de petites surprises</li><br><br>
    </ul>
</div>
</div>

<div id="calendar"></div>

{# script afficher le calendar #}
<script src="{{ asset('js/calendar.js') }}"></script>
{% endblock %}

templates/pagesInfo/cgv.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conditions générales de vente{% endblock %}

{% block body_class %}page-color-home{% endblock %}

{% block body %}

{% block bandeau %}
<div class="bandeau-info"></div>
{% endblock %}

<div class="container-mt">
    <p class="cgv">CONDITIONS GENERALES DE VENTE</p> 
    <p class="cgv">Applicables à compter du 01/01/2024</p>
    <p class="cgv">Clause n° 1 : Objet et champ d'application</p>
    
    Les présentes conditions générales de vente (CGV) constituent le socle de la négociation commerciale et sont systématiquement adressées ou remises à chaque acheteur pour lui permettre de passer commande.
    <br><br>
    Les conditions générales de vente décrites ci-après détaillent les droits et obligations de la société DOUCEUR DE LUNE et de son client dans le cadre de la vente des marchandises suivantes : ...
    <br><br>
    Toute acceptation du devis/bon de commande en ce compris la clause « Je reconnais avoir pris connaissance et j'accepte les conditions générales de vente ci-annexées » implique l'adhésion sans réserve de l'acheteur aux présentes conditions générales de vente.
    
    <p class="cgv">Clause n° 2 : Prix</p>
    
    Les prix des marchandises vendues sont ceux en vigueur au jour de la prise de commande. Ils sont libellés en euros et calculés hors taxes. Par voie de conséquence, ils seront majorés du taux de TVA et des frais de transport applicables au jour de la commande.
    
    La société DOUCEUR DE LUNE s'accorde le droit de modifier ses tarifs à tout moment. Toutefois, elle s'engage à facturer les marchandises commandées aux prix indiqués lors de l'enregistrement de la commande.
    <p class="cgv">Clause n° 3 : Rabais et ristournes</p>
    
    Les tarifs proposés comprennent les rabais et ristournes que la société DOUCEUR DE LUNE serait amenée à octroyer compte tenu de ses résultats ou de la prise en charge par l'acheteur de certaines prestations.
    <p class="cgv">Clause n° 4 : Escompte</p>
    
    Aucun escompte ne sera consenti en cas de paiement anticipé.
    <p class="cgv">Clause n° 5 : Modalités de paiement</p>
    
    Le règlement des commandes s'effectue :
    
        soit par chèque ;
        soit par carte bancaire ;
        le cas échéant, indiquer les autres moyens de paiement acceptés.
    
    Les règlements seront effectués aux conditions suivantes :
    
        Paiement à 30 jours suivant la réception des marchandises 
    
    ou
    
        Paiement à 45 jours fin de mois suivant la date de facturation 
    
    ou
    
        Paiement à 60 jours suivant la date de facturation 
    
        <p class="cgv">Clause n° 6 : Retard de paiement</p>
    
    En cas de défaut de paiement total ou partiel des marchandises livrées à l'échéance, l'acheteur doit verser à la société DOUCEUR DE LUNE une pénalité de retard égale à trois fois le taux de l'intérêt légal.
    
    Le taux de l'intérêt légal retenu est celui en vigueur au jour de la livraison des marchandises.
    
    A compter du 1er janvier 2015, le taux d'intérêt légal sera révisé tous les 6 mois (Ordonnance n°2014-947 du 20 août 2014).
    
    Cette pénalité est calculée sur le montant TTC de la somme restant due, et court à compter de la date d'échéance du prix sans qu'aucune mise en demeure préalable ne soit nécessaire.
    
    En sus des indemnités de retard, toute somme, y compris l’acompte, non payée à sa date d’exigibilité produira de plein droit le paiement d’une indemnité forfaitaire de 40 euros due au titre des frais de recouvrement.
    
    Articles 441-10 et D. 441-5 du code de commerce.
    <p class="cgv">Clause n° 7 : Clause résolutoire</p>
    
    Si dans les quinze jours qui suivent la mise en oeuvre de la clause "Retard de paiement", l'acheteur ne s'est pas acquitté des sommes restant dues, la vente sera résolue de plein droit et pourra ouvrir droit à l'allocation de dommages et intérêts au profit de la société ... (dénomination sociale).
    <p class="cgv">Clause n° 8 : Clause de réserve de propriété</p>
    
    La société ... (dénomination sociale) conserve la propriété des biens vendus jusqu'au paiement intégral du prix, en principal et en accessoires. À ce titre, si l'acheteur fait l'objet d'un redressement ou d'une liquidation judiciaire, la société ... (dénomination sociale) se réserve le droit de revendiquer, dans le cadre de la procédure collective, les marchandises vendues et restées impayées.
    <p class="cgv">Clause n° 9 : Livraison</p>
    
    La livraison est effectuée :
    
        soit par la remise directe de la marchandise à l'acheteur ;
        soit par l'envoi d'un avis de mise à disposition en magasin à l'attention de l'acheteur ;
        soit par le dépôt de la marchandise au lieu indiqué par l'acheteur sur le bon de commande.
    
    Le délai de livraison indiqué lors de l'enregistrement de la commande n'est donné qu'à titre indicatif et n'est aucunement garanti.
    
    Par voie de conséquence, tout retard raisonnable dans la livraison des produits ne pourra pas donner lieu au profit de l'acheteur à :
    
        l'allocation de dommages et intérêts ;
        l'annulation de la commande.
    
    Le risque du transport est supporté en totalité par l'acheteur.
    
    En cas de marchandises manquantes ou détériorées lors du transport, l'acheteur devra formuler toutes les réserves nécessaires sur le bon de commande à réception desdites marchandises. Ces réserves devront être, en outre, confirmées par écrit dans les cinq jours suivant la livraison, par courrier recommandé AR adressé à la société.
    <p class="cgv">Clause n° 10 : Force majeure</p>
    
    La responsabilité de la société DOUCEUR DE LUNE ne pourra pas être mise en oeuvre si la non-exécution ou le retard dans l'exécution de l'une de ses obligations décrites dans les présentes conditions générales de vente découle d'un cas de force majeure. À ce titre, la force majeure s'entend de tout événement extérieur, imprévisible et irrésistible au sens de l'article 1148 du Code civil.
    <p class="cgv">Clause n° 11 : Tribunal compétent</p>
    
    Tout litige relatif à l'interprétation et à l'exécution des présentes conditions générales de vente est soumis au droit français.
    
    À défaut de résolution amiable, le litige sera porté devant le Tribunal de commerce (lieu du siège social).
    
     
    <p class="cgv">Fait à STRASBOURG, le 30/10/2023</p>
    (signature du client) <br>
    (signature du représentant légal la société)

</div>

{% endblock %}

templates/pagesInfo/showCours.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des cours{% endblock %}

{% block body_class %}page-color-home{% endblock %}

{% block body %}

{% block bandeau %}
<div class="bandeau-info">
    <h1 class="bandeau-title">Voici les cours!</h1>
</div>
{% endblock %}

<div class="container-margin">
<div class="container-showCours">
{% for cours in listeCours|slice(0, 3) %}
    <div class="enfant enfant-cours">
        <h2>{{ cours.nomCours }}</h2> 
        <div class="img-dim">
            <img class="image-responsive" src="{{ asset('imgVich/' ~ cours.imageName) }}" alt="Image du cours">
        </div>

    <p>
        {{ cours.description|slice(0, 164)|raw }}
        <div class="more-text text-hidden">{{ cours.description|slice(164)|raw }}</div>
    </p>
        <button class="read-more-btn">Lire la suite</button>


        <p class="price2">{{ cours.prix }}€</p>
        <a class="details-link" href="{{ path('detailCours', {templateName: cours.slugCours}) }}">
            <button class="buttonMore">
            Reservez maintenant !</button>
        </a>
    </div>
{% endfor %}

    
    {% for cours in listeCours|slice(3, 3) %}
        <div class="enfant enfant-cours pastel-blue2">
            <h2>{{ cours.nomCours }}</h2> 
            <div class="img-dim"><img class="image-responsive" src="{{ asset('imgVich/' ~ cours.imageName) }}" alt="Images des cours proposés chez Douceur de lune"></div>
        <p>
            {{ cours.description|slice(0, 290)|raw }}
            <div class="more-text text-hidden">{{ cours.description|slice(290)|raw }}</div>
        </p>

        <button class="read-more-btn">Lire la suite</button>
            <p class="price2">{{ cours.prix }}€</p>
            <a class="details-link" href="{{ path('detailCours', {templateName: cours.slugCours}) }}">
                <button class="buttonMore">
                Reservez maintenant !
                    <div class="arrow-wrapper">
                        <div class="arrow"></div>
                    </div>
                </button>
            </a>
        </div>
    {% endfor %}

  {% for cours in listeCours|slice(6, 3) %}
        <div class="enfant enfant-cours pastel-blue1">
            <h2>{{ cours.nomCours }}</h2> 
            <div class="img-dim"><img class="image-responsive" src="{{ asset('imgVich/' ~ cours.imageName) }}" alt="Images des cours proposés chez Douceur de lune"></div>
            <p>{{ cours.description | raw  }}</p> 
            <p class="price2">{{ cours.prix }}€</p>
            <a class="details-link" href="{{ path('detailCours', {templateName: cours.slugCours}) }}">
                <button class="buttonMore">
                En savoir plus !
                    <div class="arrow-wrapper">
                        <div class="arrow"></div>
                    </div>
                </button>
            </a>
        </div>
    {% endfor %}

</div>
</div>

<script>

document.addEventListener('DOMContentLoaded', function () {
  var readMoreBtns = document.querySelectorAll('.read-more-btn');
  
  readMoreBtns.forEach(function(btn) {
    btn.addEventListener('click', function() {
      var text = this.parentNode.querySelector('.more-text');
      text.classList.toggle('text-hidden');
      text.classList.toggle('text-shown');
      this.textContent = text.classList.contains('text-shown') ? 'Lire moins' : 'Lire la suite';
    });
  });
});


</script>

{% endblock %}

templates/pagesInfo/showReservations.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des reservations{% endblock %}

{% block body_class %}page-color-home{% endblock %}

{% block body %}

{% block bandeau %}
<div class="bandeau-info"></div>
{% endblock %}

<div class="container-margin">
    <div class="container-showReservations">
       
        <table class="reservations-table">
            
            <thead>
                <tr>
                    <th>Pseudo</th>
                    <th>Téléphone</th>
                    <th>Cours</th>
                    <th>Date de réservation</th>
                    <th>Date du cours</th>
                </tr>
            </thead>
            
            <tbody>
                {% for reservation in reservations|reverse|slice(0, 10) %}
                <tr>
                    {% if reservation.user != null %}
                    <td>{{ reservation.userLastname }} {{ reservation.userFirstname }}</td>
                    <td class="td-color">
                        <a href="tel:{{ reservation.userPhone|split('', 2)|join(' ') }}">
                            {{ reservation.userPhone|split('', 2)|join(' ') }}
                        </a>
                    </td>
                    {% else %}
                    <td>Utilisateur supprimé</td>
                    <td>Utilisateur supprimé</td>
                    {% endif %}
                    <td>{{ reservation.cours }}</td>
                    <td>{{ reservation.dtResa | date("m/d/Y") }}</td>
                    <td>{{ reservation.dtCours | date("m/d/Y") }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}